---
# List of plays
-
  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: always

  # Vars: variables that will apply to the play, on all targets 

  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    # from https://superuser.com/questions/1395954/ansible-playbook-to-determine-os-release
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  - name: Verify install_files is present
    debug: msg="install_files/_README = {{ lookup('file', '/home/kasm-default-profile/install_files/_README') }}"  
    # Detect if we are running on a WSL2 environment
  - name: Verify install_files is present
    debug: msg="install_files/_README = {{ lookup('file', '/home/kasm-default-profile/install_files/_README') }}"
    # Detect if we are running on a WSL2 environment
  - name: Set wsl2_environment fact default to false
    set_fact:
      wsl2_environment: false
  - name: Set wsl2_environment fact True
    set_fact:
      wsl2_environment: true
    when: ansible_kernel is search("microsoft-standard-WSL2")  
  # fix for .gnupg/ permissions when building custom images
  - name: Add fix for .gnupg/ permissions
    lineinfile:
      path: "/etc/bash.bashrc"
      line: "chmod 700 ~/.gnupg/"    
  - name: Add custom prompt to /etc/skel/.profile
    lineinfile:
      path: "/etc/skel/.profile"
      line: 'export PS1="\[\033[00;32m\][\w]\$\[\033[00m\] "'

  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task

  # Roles: list of roles to be imported into the play
  roles:
  - role: irixjp.role_example_hello

# Add additional plays here (remember the list entry -)
# Be sure to use the same hosts and connection entries above
# addtional plays

-
  # Install build-essential
  hosts: localhost
  connection: local
  tags:
  - install_plantuml
  - install_generator_asciidoctor
  - install_doctools

  tasks:
  - name: Install build-essential
    apt:
      name: build-essential
      update_cache: yes

-
  # install firefox
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
  - install_firefox

  vars:
    firefox_profiles:
      default:
        extensions:
          - ublock-origin
        preferences:
          network.cookie.cookieBehavior: 1
          privacy.donottrackheader.enabled: true
          datareporting.healthreport.uploadEnabled: false
      secondprofile:
        extensions:
          - adblock-plus
        preferences:
          privacy.donottrackheader.enabled: false
          privacy.trackingprotection.enabled: false
          signon.rememberSignons: false
          datareporting.healthreport.uploadEnabled: false

  pre_tasks:
  - name: Update apt packages
    apt:
      update_cache: yes

  roles:
    - role: staticdev.firefox

-
  # install keychain, git, and @capsulecorplab .vimrc and .gitconfig
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_utilities

  vars:
    git_version: "2.43.0"
    git_version_to_install: "1:{{ git_version }}-0ppa1~ubuntu22.04.1"
    keychain_version: "2.8.5"
    keychain_version_to_install: "{{ keychain_version }}-2"
    keychain_version_expected: "{{ keychain_version }}.."

  tasks:
  - name: Add git PPA
    shell: add-apt-repository ppa:git-core/ppa
  - name: Install git
    apt:
      name: "git={{ git_version_to_install }}"
  - name: Install Git Bash Completion
    apt:
      name: bash-completion
      update_cache: yes
  - name: Install Keychain
    apt:
      name: "keychain={{ keychain_version_to_install }}"
      update_cache: yes
  - name: install ping
    apt:
      name: iputils-ping
      update_cache: yes
  - name: Get git version
    shell: git version | sed 's/[[:alpha:]|(|[:space:]]//g'
    register: installed_git_version
  - name: Get keychain version
    shell:
      cmd: keychain -V 2> >(grep -i keychain) 2> >(sed 's/[[:alpha:]|(|[:space:]]//g') | fgrep '*' | sed 's/[*~://]//g'
      executable: /bin/bash
    register: installed_keychain_version
  - name: Display git and keychain versions
    debug:
      msg: "git = {{ installed_git_version.stdout }} | keychain = {{ installed_keychain_version.stdout }}"
  - name: Test git version
    fail:
      msg: "Git Version Error: Expected {{ git_version }} | Found {{ installed_git_version.stdout }}"
    when: installed_git_version.stdout != git_version
  - name: Test keychain version
    fail:
      msg: "Keychain Version Error: Expected {{ keychain_version_expected }} | Found {{ installed_keychain_version.stdout }}"
    when: installed_keychain_version.stdout != keychain_version_expected
  - name: auto-launch keychain in shell, if ssh keys exists
    shell: echo 'if [ -r ~/.ssh/id_ed25519 ]; then\n    eval `keychain --eval id_ed25519`\nfi' >> /home/kasm-default-profile/.bashrc
  - name: Install @capsulecorplab .vimrc
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/495058e7a57ed8adaed3c40c80d09739/raw/4a6e6f6ff92b96919be111c9cbb5a4a21ab472d2/.vimrc
      dest: /home/kasm-default-profile/
  - name: Install @capsulecorplab .gitconfig
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/401ba2fe0857a328f2a626adbf078cc6/raw/b89a6234f0d620ff60bcfe37f95de197b8772377/.gitconfig
      dest: /home/kasm-default-profile/

-
  # install PrusaSlicer
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
    - install_oshw_tools
    - install_prusaslicer

  vars:
    prusaslicer_version: 2.7.0
    prusaslicer_release_date: 202311231454
    prusaslicer_dir: "PrusaSlicer-{{ prusaslicer_version }}+linux-x64-GTK3-{{ prusaslicer_release_date }}"

  tasks:
  - name: Join parts of PrusaSlicer tarball
    shell: cat /home/kasm-default-profile/install_files/{{ prusaslicer_dir }}.tar.bz2.parta* > /home/kasm-default-profile/install_files/{{ prusaslicer_dir }}.tar.bz2
  - name: Extract PrusaSlicer for 64-bit Linux to /opt
    unarchive:
      src: /home/kasm-default-profile/install_files/{{ prusaslicer_dir }}.tar.bz2
      dest: /opt
      remote_src: yes
      creates: /opt/{{ prusaslicer_dir }}/bin/prusa-slicer
  - name: Create symlink for prusa-slicer in /usr/local/bin
    shell: ln -srv /opt/{{ prusaslicer_dir }}/bin/prusa-slicer /usr/local/bin/prusa-slicer
  - name: Configure PrusaSlicer desktop shortcut
    shell: echo "[Desktop Entry]\nName=PrusaSlicer\nGenericName=PrusaSlicer\nExec=/usr/local/bin/prusa-slicer\nIcon=/opt/{{ prusaslicer_dir }}/resources/icons/PrusaSlicer.png\nTerminal=false\nType=Application\nStartupNotify=false\nCategories=Application;Development;" > /usr/share/applications/prusaslicer.desktop
  - name: Get prusa-slicer version
    shell: prusa-slicer --help | grep PrusaSlicer- | awk '{ print $1 '}
    register: installed_prusaslicer_version
  - name: Display prusa-slicer version
    debug:
      msg: "prusa-slicer = {{ installed_prusaslicer_version.stdout }}"
  - name: Test prusa-slicer version
    fail:
      msg: "prusa-slicer Error: Expected {{ prusaslicer_dir }} | Found {{ installed_prusaslicer_version.stdout }}"
    when: installed_prusaslicer_version.stdout != prusaslicer_dir

-
  # install OpenSCAD
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
    - install_oshw_tools
    - install_openscad

  vars:
    openscad_version: "2021.01"
    openscad_version_to_install: "{{ openscad_version }}-4build1"

  tasks:
  - name: Install openscad
    apt:
      name: "openscad={{ openscad_version_to_install }}"
  - name: Get OpenSCAD version
    shell: openscad --info | grep 'OpenSCAD Version' | awk '{ print $3 '}
    register: installed_openscad_version
  - name: Display OpenSCAD version
    debug:
      msg: "OpenSCAD = {{ installed_openscad_version.stdout }}"
  - name: Test OpenSCAD version
    fail:
      msg: "OpenSCAD Version Error: Expected {{ openscad_version }} | Found {{ installed_openscad_version.stdout }}"
    when: installed_openscad_version.stdout != openscad_version

-
  # install Python packages with pip
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Update OS to point python to python3
    apt:
      name: python-is-python3
      update_cache: yes
  - name: Install pip for python3 with Apt
    apt:
      name: python3-pip
      update_cache: yes
  - name: Install python packages with pip
    pip:
      name:
        - jupyterlab
        - notebook
        - voila
        - pint

-
  # install ASCII Doctor
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
  - install_generator_asciidoctor
  - install_doctools

  vars:
    asciidoctor_version: 2.0.17
    asciidoctor_version_expected: "{{ asciidoctor_version }}[.]"

  tasks:
  - name: Install Ruby
    apt:
      name: ruby-full
      update_cache: yes
  - name: Run gem install for asciidoctor
    shell:
      cmd: "gem install asciidoctor -v {{ asciidoctor_version }}"
  - name: Install hexapdf dependencies
    apt:
      name: libssl-dev
      update_cache: yes
  - name: Install PlantUML and PDF support
    shell:
      cmd: gem install asciidoctor-diagram rghost hexapdf text-hyphen rouge pygments.rb coderay asciidoctor-pdf
  - name: Get asciidoctor version
    shell: asciidoctor --version | grep Asciidoctor | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/[*~://]//g'
    register: installed_asciidoctor_version
  - name: Display asciidoctor version
    debug:
      msg: "ASCII Doctor = {{ installed_asciidoctor_version.stdout }}"
  - name: Test asciidoctor version
    fail:
      msg: "ASCII Doctor Version Error: Expected {{ asciidoctor_version_expected }} | Found {{ installed_asciidoctor_version.stdout }}"
    when: installed_asciidoctor_version.stdout != asciidoctor_version_expected

-
  # install QOwnNotes
  hosts: localhost
  connection: local
  tags:
  - install_doctools

  vars:
    qownnotes_version: "23.11.3"
    qownnotes_version_to_install: "{{ qownnotes_version }}-1ubuntu3ppa1~jammy1"

  tasks:
  - name: Add qownnotes PPA
    shell: add-apt-repository ppa:pbek/qownnotes
  - name: Install QOwnNotes
    apt:
      name: "qownnotes={{ qownnotes_version_to_install }}"
      update_cache: yes

- 
  # install sudo for the vs-code role below 
  hosts: localhost
  connection: local
  tasks:
  - name: Install Sudo
    apt:
      name: sudo
      update_cache: yes
  - name: Preserve DONT_PROMPT_WSL_INSTALL in sudoers
    lineinfile:
      path: "/etc/sudoers"
      line: "Defaults        env_keep += \"DONT_PROMPT_WSL_INSTALL\""
    when: wsl2_environment

-
# add dev user to give vs code somewhere to install extensions
  hosts: localhost
  connection: local
  tasks:
  - name: Add dev user
    user:
      name: dev
      uid: 1001

-
  # install the remainder of the tools
  hosts: localhost
  connection: local
  environment: 
    DONT_PROMPT_WSL_INSTALL: 1
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "dev"
          visual_studio_code_extensions:
            - ms-python.python
            - dendron.dendron
            - foam.foam-vscode
            - eamodio.gitlens
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "extensions.ignoreRecommendations": true,
            "update.mode": "none",
            "extensions.autoUpdate": false,
            "extensions.autoCheckUpdates": false,
            "terminal.integrated.profiles.linux": {
              "bash (login)": {
                "path": "bash",
                "args": ["-l"]
                }
              },
            "terminal.integrated.defaultProfile.linux": "bash (login)" 
          }  

-
  # install PlantUML
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
  - install_plantuml
  - install_doctools

  vars:
    jdk_version: 2:1.11-72build2
    graphviz_version_expected: "dot - graphviz version 2.50.0 (20211204.2007)"

  tasks:
  - name: Install JDK
    apt:
      name: "default-jdk={{ jdk_version }}"
      update_cache: yes
  - name: Get JDK Version
    shell: java --version | grep -m 1 -i openjdk
    register: installed_jdk_version
  - name: Install pre-reqs to build graphviz
    apt:
      name: libcairo2-dev, libexpat-dev, libfreetype-dev, libgd-dev, fontconfig-config, libglib2.0-dev, libgtk2.0-dev, libpng-dev, zlib1g-dev, libsdl-pango-dev, libgts-bin, libgtk-3-dev, libgtkglext1-dev, glade, freeglut3-dev, autoconf, automake, bison, flex, ghostscript, libtool, pkg-config, swig
      update_cache: yes
  - name: Expand source files archive
    unarchive:
      src: /home/kasm-default-profile/install_files/graphviz-2.50.0.tar.gz
      dest: /home/kasm-default-profile/install_files/
      remote_src: yes
      creates: /home/kasm-default-profile/install_files/graphviz-2.50.0/README
  - name: Build graphviz
    shell:
      cmd: ./configure --enable-perl=no && make > /tmp/graphviz_build_output.txt 2>&1 && make install
      chdir: /home/kasm-default-profile/install_files/graphviz-2.50.0/
      executable: /bin/bash
  - name: Get graphviz version
    shell: dot -V
    register: installed_graphviz_version
  - name: install plantuml
    copy:
      src: /home/kasm-default-profile/install_files/plantuml.jar
      dest: /usr/local/bin/plantuml.jar
      remote_src: yes
  - name: Display JDK and GraphViz versions
    debug:
      msg: "JDK = {{ installed_jdk_version.stdout }} | graphviz = {{ installed_graphviz_version.stderr }}"
  - name: Test Graphviz version
    fail:
      msg: "Graphviz Version Error: Expected {{ graphviz_version_expected }} | Found {{ installed_graphviz_version.stderr }}"
    when: installed_graphviz_version.stderr != graphviz_version_expected

-
  # Copy VS Code changes to kasm-default-profile and lean up (remove) dev user now that vs code is installed
  hosts: localhost
  connection: local
  tasks:
  - name: Copy VS Code changes to kasm-default-profile
    shell: 
      cmd: cp -r /home/dev/.config/Code/ /home/kasm-default-profile/.config/Code/ && cp -r /home/dev/.vscode/ /home/kasm-default-profile/.vscode/
  - name: Remove dev user
    user:
      name: dev
      state: absent
      remove: yes 

# Three dots indicate the end of a YAML document
...
